version: '3'
services:
  router:
    restart: always
    image: mab105120/multi-router
    ports:
      - "80:80"
    mem_limit: 128m
    hostname: router
  client:
    image: mab105120/multi-client
    mem_limit: 128m
    hostname: client
  app:
    image: mab105120/multi-server
    mem_limit: 128m
    hostname: app
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGHOST=$PGHOST
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGDATABASE=$PGDATABASE
      - PGPORT=$PGPORT
  worker:
    image: mab105120/multi-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    