name: Docker image build

# When will this workflow execute? 
# 1. on pushes to any branches (except master because master will be a protected branch)
# 2. on pull requests from any branch to master
on:
  push:
    branches:
      - '**' # all branches
      - '!master' # except master
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3 # check out the code from the branch that executed the build
    - name: Build a test docker image to run the tests
      run: docker build ./client --file ./client/Dockerfile.dev --tag mab105120/client-test
    - name: Run tests
      run: docker run -e CI=true mab105120/client-test npm test
    - name: Build docker images
      run: |
        docker build ./client --tag mab105120/multi-client
        docker build ./server --tag mab105120/multi-server
        docker build ./router --tag mab105120/multi-router
        docker build ./worker --tag mab105120/multi-worker
    - name: Log in to Docker Hub
      env:
        DOCKER_ID: ${{ secrets.DOCKER_ID }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      uses: docker/login-action@v2 # https://github.com/marketplace/actions/docker-login
      with:
        username: $DOCKER_ID
        password: $DOCKER_ACCESS_TOKEN
    - name: Push images to Docker Hub
      run: |
        docker push mab105120/multi-client
        docker push mab105120/multi-server
        docker push mab105120/multi-router
        docker push mab105120/multi-worker
